#!/home/cuizc/envs/pyramidproj/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'brms==0.0','console_scripts','initialize_brms_db'
__requires__ = 'brms==0.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('brms==0.0', 'console_scripts', 'initialize_brms_db')()
    )
